### ISSUE TITLE
Github issue

### ISSUE THREAD

**Issue by sheri-thomson** [sheri-thomson/me-oh-my-html#1]
@thomasjbradley 

I began this code over the Summer but was unable to push any of my commits. I thought it was because I didn't have access to the course at that time, but even now I can't push them. Also, after changing my username on github for the progressinator, now when i click on thom0610 (which hasn't updated to sheri-thomson), I get an error code that the page doesn't exist. 

<img width="962" alt="Screen Shot 2019-09-11 at 6 36 49 PM" src="https://user-images.githubusercontent.com/31968878/64740574-c1fff880-d4c3-11e9-80f5-c88759e21f55.png">

<img width="1644" alt="Screen Shot 2019-09-11 at 6 43 58 PM" src="https://user-images.githubusercontent.com/31968878/64740748-6124f000-d4c4-11e9-99a4-2c76d056b0de.png">

**Comment by thomasjbradley** [comment]
The username doesn’t automatically change on Progressinator—I’ve changed it in the database now so it should start working.

**Comment by thomasjbradley** [comment]
For the `me-oh-my-html` assignment, did you fork it? In the menu go to `Repository > Repository Settings`. In the URL that’s shown, do you see your username? Or one of my Web Dev usernames?

Also, try going to menu `GitHub Desktop > Preferences` & sign out and sign back in.

**Comment by sheri-thomson** [comment]
<img width="1162" alt="Screen Shot 2019-09-12 at 12 42 58 PM" src="https://user-images.githubusercontent.com/31968878/64803500-e955d480-d55a-11e9-97e2-b5f1b9067cf8.png">

<img width="1117" alt="Screen Shot 2019-09-12 at 12 42 50 PM" src="https://user-images.githubusercontent.com/31968878/64803509-eeb31f00-d55a-11e9-8d73-738163cdadb3.png">

**Comment by thomasjbradley** [comment]
Is GitHub desktop’s repo URL pointing properly?

**Comment by sheri-thomson** [comment]
From the app in my dock? Where would I see that?

**Comment by thomasjbradley** [comment]
Yes, in the GitHub Desktop app.

In the menu go to Repository > Repository Settings. In the URL that’s shown, do you see your username? Or one of my Web Dev usernames?

**Comment by sheri-thomson** [comment]
It the old username 
https://github.com/thom0610/me-oh-my-html.git

Not the sheri-thomson username

**Comment by thomasjbradley** [comment]
Okay! Type in that box and change it to the new username. And save.

**Comment by sheri-thomson** [comment]
When I changed my username it sent me to a page to reroute my urls .. but I didn't know how to make sense of it 

https://help.github.com/en/articles/changing-a-remotes-url

**Comment by sheri-thomson** [comment]
Perfect! I was able to submit my assignment :) 
Thank you so much ..
